server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0